spring:
  application:
    name: employee-service
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    show_sql: true
    generate-ddl: true
  h2:
    console:
      enabled: true